name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      TESTDINO_API_KEY: ${{ secrets.TESTDINO_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run smoke tests
        run: xvfb-run -a npx playwright test --grep @smoke

      - name: Run regression tests
        run: xvfb-run -a npx playwright test --grep @regression

      - name: Upload trace artifacts
        if: failure() # Only upload traces on failure to save storage
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/trace.zip

      - name: Upload Playwright Artifacts
        if: always() # Upload report regardless of pass/fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-${{ github.sha }}
          path: |
            playwright-report